# Generated by Django 4.1.3 on 2023-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=16)),
                ('disputes', models.IntegerField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'Euro'), ('JPY', 'Japanese yen')], max_length=3)),
                ('active', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('plan', models.ManyToManyField(related_name='plans', to='pricing.plans')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
