# Generated by Django 4.1.3 on 2023-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='plan',
        ),
        migrations.AddField(
            model_name='plans',
            name='feature',
            field=models.ManyToManyField(related_name='features', to='pricing.feature'),
        ),
    ]
