# Generated by Django 4.1.3 on 2023-05-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_remove_feature_plan_plans_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY')], max_length=3),
        ),
    ]
