# Generated by Django 4.1.3 on 2023-05-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_plans_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='description',
            field=models.CharField(default="None", max_length=192),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='stripe_product_id',
            field=models.CharField(default="None", max_length=48),
        ),
    ]
