# Generated by Django 4.1.3 on 2023-05-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_plans_description_plans_stripe_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
