# Generated by Django 4.1.3 on 2023-05-31 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='plan',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pricing.plan'),
            preserve_default=False,
        ),
    ]
