# Generated by Django 4.1.3 on 2023-06-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_paymentdetail_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
