# Generated by Django 4.1.3 on 2023-06-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0076_alter_settlementagreements_content'),
        ('pricing', '0008_paymentdetail_is_subscription_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorDisputeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disputes_created', models.IntegerField()),
                ('disputes_available', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_count', to='litigation.creator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
