# Generated by Django 4.1.3 on 2023-06-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0076_alter_settlementagreements_content'),
        ('pricing', '0009_creatordisputecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='actor',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='litigation.creator'),
            preserve_default=False,
        ),
    ]
