# Generated by Django 4.1.3 on 2023-01-02 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('litigation', '0041_merge_20221206_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('display_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_strike', models.BooleanField(blank=True, default=False, null=True)),
                ('is_caucus', models.BooleanField(blank=True, default=False, null=True)),
                ('is_mediator', models.BooleanField(blank=True, default=False, null=True)),
                ('is_blur', models.BooleanField(blank=True, default=False, null=True)),
                ('is_party_attributed', models.BooleanField(blank=True, default=False, null=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='litigation.dispute')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane', to='noteboard.lane')),
                ('parent', models.ManyToManyField(blank=True, null=True, related_name='linked_notes', to='noteboard.note')),
            ],
        ),
    ]
