# Generated by Django 4.1.3 on 2023-01-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteboard', '0002_alter_note_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='noteboard.lane'),
        ),
    ]
