# Generated by Django 4.1.3 on 2023-01-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteboard', '0003_alter_note_lane'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('base_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_proposal', to='noteboard.note')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noteboard.note')),
            ],
        ),
    ]
