# Generated by Django 4.1.3 on 2023-01-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteboard', '0005_note_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalrelation',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='noteboard.note'),
        ),
    ]
