# Generated by Django 4.1.5 on 2023-01-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteboard', '0006_alter_proposalrelation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='is_proposal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='countered',
            field=models.BooleanField(default=False),
        ),
    ]
