# Generated by Django 4.1.3 on 2023-02-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteboard', '0007_lane_is_proposal_note_countered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lane',
            options={'permissions': [('view_noteboard', 'Can view noteboard')]},
        ),
    ]
