# Generated by Django 4.1.5 on 2023-01-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsheet', '0002_termsheet_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontitle',
            name='text',
            field=models.CharField(max_length=40),
        ),
    ]
