# Generated by Django 4.1.5 on 2023-02-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsheet', '0004_digitalsignature_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalsignature',
            name='text',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='termsheet',
            name='title',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='termsheetsection',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='termsheettitle',
            name='text',
            field=models.CharField(max_length=40),
        ),
    ]
