# Generated by Django 4.1.3 on 2023-02-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termsheet', '0005_alter_digitalsignature_text_alter_termsheet_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsheet',
            options={'permissions': [('print_termsheet', 'Can print termsheet')]},
        ),
    ]
