# Generated by Django 4.1.2 on 2022-10-28 02:01

from django.db import migrations, models
import litigation.models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuid',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
