# Generated by Django 4.1.2 on 2022-10-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0004_rename_actor_actor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=90, on_delete=django.db.models.deletion.CASCADE, to='litigation.actor'),
            preserve_default=False,
        ),
    ]
