# Generated by Django 4.1.2 on 2022-10-31 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('litigation', '0005_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='notes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('In-progress', 'In-progress'), ('Resolved', 'Resolved'), ('Unresolved', 'Unresolved'), ('pending-signup', 'Pending-signup')], max_length=16)),
                ('code', models.CharField(max_length=24)),
                ('type', models.CharField(max_length=24)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dispute_Claimer', to='litigation.claimer')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dispute_Creator', to='litigation.creator')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litigation.respondent')),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='litigation.dispute'),
        ),
    ]
