# Generated by Django 4.1.2 on 2022-11-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0006_alter_actor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='actor',
        ),
    ]
