# Generated by Django 4.1.2 on 2022-11-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0006_claim_notes_dispute_alter_claim_id'),
        ('litigation', '0007_rename_user_address_actor'),
    ]

    operations = [
    ]
