# Generated by Django 4.1.2 on 2022-11-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0008_merge_20221101_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='actor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='notes',
        ),
        migrations.AlterField(
            model_name='dispute',
            name='claimer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputed_claimed', to='litigation.claimer'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_created', to='litigation.creator'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('waiting', 'in-progress'), ('accepted', 'answered'), ('unanswered', 'unanswered'), ('pending-signup', 'pending-signup')], max_length=16),
        ),
    ]
