# Generated by Django 4.1.2 on 2022-11-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0009_rename_actor_address_user_remove_claim_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='claimer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_claimed', to='litigation.claimer'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='code',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='litigation.respondent'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='type',
            field=models.CharField(choices=[('hearing', 'hearing')], max_length=24),
        ),
    ]
