# Generated by Django 4.1.2 on 2022-11-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0012_alter_dispute_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='litigation.creator'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes_responded', to='litigation.respondent'),
        ),
    ]
