# Generated by Django 4.1.2 on 2022-11-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0013_alter_dispute_creator_alter_dispute_respondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='second_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
