# Generated by Django 4.1.3 on 2022-11-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0014_alter_address_second_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuid',
            name='dispute_id',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='litigation.dispute'),
            preserve_default=False,
        ),
    ]
