# Generated by Django 4.1.3 on 2022-11-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0015_uuid_dispute_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uuid',
            old_name='dispute_id',
            new_name='dispute',
        ),
    ]
