# Generated by Django 4.1.3 on 2022-11-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0019_alter_address_first_address_alter_dispute_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='claimer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_claimed', to='litigation.claimer'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_responded', to='litigation.respondent'),
        ),
    ]
