# Generated by Django 4.1.3 on 2022-11-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('litigation', '0020_alter_offer_counter_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(
                choices=[('pending', 'pending'), ('counter_offer', 'counter-offer'), ('rejected', 'rejected'),
                         ('accepted', 'accepted')], max_length=16),
        ),
    ]
