# Generated by Django 4.1.3 on 2022-11-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0021_alter_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
