# Generated by Django 4.1.3 on 2022-11-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0016_rename_dispute_id_uuid_dispute'),
        ('litigation', '0022_alter_evidence_attachment'),
        ('litigation', '0023_claim_offer_evidence'),
    ]

    operations = [
    ]
