# Generated by Django 4.1.3 on 2022-11-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0024_merge_20221123_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claimed_amount',
            field=models.CharField(default=500, max_length=8),
            preserve_default=False,
        ),
    ]
