# Generated by Django 4.1.3 on 2022-11-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0024_merge_20221117_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='litigation.actor'),
            preserve_default=False,
        ),
    ]
