# Generated by Django 4.1.3 on 2022-11-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0020_alter_dispute_claimer_alter_dispute_respondent'),
        ('litigation', '0025_evidence_creator'),
    ]

    operations = [
    ]
