# Generated by Django 4.1.3 on 2022-11-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0026_merge_20221118_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='litigation.actor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='relation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='litigation.witness'),
        ),
    ]
