# Generated by Django 4.1.3 on 2022-11-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0027_actor_creator_actor_relation_dispute_witness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='litigation.witness'),
        ),
    ]
