# Generated by Django 4.1.3 on 2022-11-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0028_alter_dispute_witness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='counter_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='counter_amount_currency',
        ),
    ]
