# Generated by Django 4.1.3 on 2022-11-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0029_remove_offer_counter_amount_and_more'),
        ('litigation', '0031_alter_address_state'),
    ]

    operations = [
    ]
