# Generated by Django 4.1.3 on 2022-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0032_merge_20221125_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='display-pictures/'),
        ),
    ]
