# Generated by Django 4.1.3 on 2022-11-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0032_merge_20221125_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='dispute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='litigation.dispute'),
        ),
    ]
