# Generated by Django 4.1.3 on 2022-11-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0025_claim_claimed_amount'),
        ('litigation', '0033_alter_claim_dispute'),
    ]

    operations = [
    ]
