# Generated by Django 4.1.3 on 2022-11-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0034_merge_20221127_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='dispute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='litigation.dispute'),
        ),
    ]
