# Generated by Django 4.1.3 on 2022-11-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0030_alter_offer_updated_at'),
        ('litigation', '0035_alter_claim_dispute'),
    ]

    operations = [
    ]
