# Generated by Django 4.1.3 on 2022-11-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0036_remove_dispute_witness_actor_dispute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='dispute',
        ),
        migrations.AddField(
            model_name='dispute',
            name='witness',
            field=models.ManyToManyField(blank=True, to='litigation.witness'),
        ),
    ]
