# Generated by Django 4.1.3 on 2022-11-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0036_merge_20221128_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='amount',
            new_name='offered_amount',
        ),
    ]
