# Generated by Django 4.1.3 on 2022-11-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0037_remove_actor_dispute_dispute_witness'),
        ('litigation', '0037_rename_amount_offer_offered_amount'),
    ]

    operations = [
    ]
