# Generated by Django 4.1.3 on 2022-11-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0038_merge_20221129_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='claimer_invitation_status',
            field=models.CharField(choices=[('sent', 'sent'), ('draft', 'draft'), ('pending', 'pending'), ('signed-up', 'signed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='respondent_invitation_status',
            field=models.CharField(choices=[('sent', 'sent'), ('draft', 'draft'), ('pending', 'pending'), ('signed-up', 'signed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='witness',
            field=models.ManyToManyField(blank=True, related_name='disputes_witnessed', to='litigation.witness'),
        ),
    ]
