# Generated by Django 4.1.3 on 2022-12-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0039_alter_dispute_claimer_invitation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='contains_witness',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='claimer_invitation_status',
            field=models.CharField(choices=[('sent', 'sent'), ('draft', 'draft'), ('pending', 'pending'), ('signed', 'signed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='respondent_invitation_status',
            field=models.CharField(choices=[('sent', 'sent'), ('draft', 'draft'), ('pending', 'pending'), ('signed', 'signed')], default='pending', max_length=16),
        ),
    ]
