# Generated by Django 4.1.3 on 2022-12-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0033_actor_display_picture'),
        ('litigation', '0040_dispute_contains_witness_and_more'),
    ]

    operations = [
    ]
