# Generated by Django 4.1.3 on 2022-12-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0041_merge_20221206_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='arbitrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_assigned', to='litigation.arbitrator'),
        ),
    ]
