# Generated by Django 4.1.3 on 2023-01-05 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0042_dispute_arbitrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='litigation.actor'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='litigation.claim'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='litigation.claim'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='litigation.actor'),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='actor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timezone', to='litigation.actor'),
        ),
    ]
