# Generated by Django 4.1.5 on 2023-02-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0043_alter_address_user_alter_evidence_claim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('deadline_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='litigation.dispute')),
            ],
        ),
    ]
