# Generated by Django 4.1.5 on 2023-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0045_alter_timeline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='deadline_date',
            field=models.DateField(),
        ),
    ]
