# Generated by Django 4.1.5 on 2023-02-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0045_alter_dispute_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='witness',
            field=models.ManyToManyField(blank=True, to='litigation.witness'),
        ),
    ]
