# Generated by Django 4.1.5 on 2023-02-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0046_alter_timeline_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='litigation.dispute'),
        ),
    ]
