# Generated by Django 4.1.5 on 2023-02-24 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0046_alter_dispute_witness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='litigation.creator'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='witness',
            field=models.ManyToManyField(blank=True, related_name='disputes_witnessed', to='litigation.witness'),
        ),
    ]
