# Generated by Django 4.1.5 on 2023-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0047_alter_timeline_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
