# Generated by Django 4.1.5 on 2023-02-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0044_alter_claim_claimed_amount'),
        ('litigation', '0048_timeline_end_date'),
    ]

    operations = [
    ]
