# Generated by Django 4.1.5 on 2023-02-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0049_alter_dispute_witness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='witness',
            field=models.ManyToManyField(related_name='disputes_witnessed', to='litigation.witness'),
        ),
    ]
