# Generated by Django 4.1.3 on 2023-02-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0049_merge_20230211_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={'permissions': [('view_disputes_table', 'Can view disputes table')]},
        ),
    ]
