# Generated by Django 4.1.5 on 2023-02-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0051_alter_dispute_witness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='type',
            field=models.SlugField(choices=[('arbitrator', 'Arbitrator'), ('claimer', 'Claimer'), ('creator', 'Creator'), ('witness', 'Witness'), ('respondent', 'Respondent')], default='Witness', max_length=25),
            preserve_default=False,
        ),
    ]
