# Generated by Django 4.1.5 on 2023-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0052_alter_actor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='type',
            field=models.SlugField(blank=True, choices=[('arbitrator', 'Arbitrator'), ('claimer', 'Claimer'), ('creator', 'Creator'), ('witness', 'Witness'), ('respondent', 'Respondent')], max_length=25, null=True),
        ),
    ]
