# Generated by Django 4.1.5 on 2023-03-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0050_alter_dispute_options'),
        ('litigation', '0053_alter_actor_type'),
    ]

    operations = [
    ]
