# Generated by Django 4.1.5 on 2023-03-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0054_merge_20230316_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='contains_witness',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
