# Generated by Django 4.1.5 on 2023-03-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0057_alter_actionnames_action_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionnames',
            options={'verbose_name_plural': 'Action Names'},
        ),
        migrations.AlterModelOptions(
            name='actions',
            options={'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='disputeactoractions',
            options={'verbose_name_plural': 'Dispute Actor Actions'},
        ),
        migrations.RenameField(
            model_name='actionnames',
            old_name='action_name',
            new_name='name',
        ),
    ]
