# Generated by Django 4.1.5 on 2023-03-09 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0058_alter_actionnames_options_alter_actions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='action',
        ),
        migrations.RemoveField(
            model_name='disputeactoractions',
            name='action',
        ),
        migrations.RemoveField(
            model_name='disputeactoractions',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='disputeactoractions',
            name='dispute',
        ),
        migrations.DeleteModel(
            name='ActionNames',
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.DeleteModel(
            name='DisputeActorActions',
        ),
    ]
