# Generated by Django 4.1.5 on 2023-03-09 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0059_remove_actions_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Approve', 'Approve'), ('Straight to hearing', 'Straight to hearing')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Action Names',
            },
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], max_length=24)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_values', to='litigation.actionnames')),
            ],
            options={
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='DisputeActorActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ManyToManyField(to='litigation.actions')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='litigation.actor')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='litigation.dispute')),
            ],
            options={
                'verbose_name_plural': 'Dispute Actor Actions',
            },
        ),
    ]
