# Generated by Django 4.1.3 on 2023-04-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0055_alter_dispute_contains_witness'),
        ('litigation', '0060_actionnames_actions_disputeactoractions'),
    ]

    operations = [
    ]
