# Generated by Django 4.1.3 on 2023-04-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0061_merge_20230407_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_code', models.CharField(max_length=12)),
                ('template_title', models.CharField(max_length=24)),
                ('email_subject', models.CharField(max_length=48)),
                ('content', models.CharField(max_length=120)),
            ],
        ),
    ]
