# Generated by Django 4.1.3 on 2023-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0063_emailtemplate_actor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
