# Generated by Django 4.1.3 on 2023-04-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0064_alter_emailtemplate_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='dispute_code',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='dispute',
            field=models.ForeignKey(default=158, on_delete=django.db.models.deletion.CASCADE, to='litigation.dispute'),
            preserve_default=False,
        ),
    ]
