# Generated by Django 4.1.3 on 2023-04-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0066_remove_emailtemplate_actor_type_emailtemplate_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_template', to='litigation.actor'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_template', to='litigation.dispute'),
        ),
    ]
