# Generated by Django 4.1.3 on 2023-04-11 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0067_alter_emailtemplate_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='attachment',
            field=models.FileField(upload_to='evidences/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png', 'mp4', '.xls', '.xlsx'])]),
        ),
    ]
