# Generated by Django 4.1.3 on 2023-05-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0068_alter_evidence_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementAgreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=48)),
                ('content', models.CharField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='litigation.dispute')),
            ],
        ),
    ]
