# Generated by Django 4.1.3 on 2023-05-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0069_settlementagreements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlementagreements',
            name='template_name',
        ),
    ]
