# Generated by Django 4.1.3 on 2023-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0073_alter_settlementagreements_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='congratulatory_modal_rendered',
            field=models.BooleanField(default=False),
        ),
    ]
