# Generated by Django 4.1.3 on 2023-05-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0075_rename_congratulatory_modal_rendered_offer_offer_accepted_modal_rendered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementagreements',
            name='content',
            field=models.TextField(max_length=50000),
        ),
    ]
