# Generated by Django 4.1.3 on 2023-01-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('litigation', '0043_alter_address_user_alter_evidence_claim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(choices=[('C', 'Caucus'), ('P', 'Plenary')], default='P', max_length=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='litigation.actor')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='litigation.dispute')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='litigation.actor')),
            ],
        ),
    ]
