# Generated by Django 4.1.3 on 2023-01-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='notes',
        ),
        migrations.AddField(
            model_name='timelog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
