# Generated by Django 4.1.3 on 2023-01-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0002_remove_timelog_notes_timelog_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
