# Generated by Django 4.1.3 on 2023-01-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0003_alter_timelog_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='type',
            field=models.CharField(choices=[('C', 'Caucus'), ('P', 'Plenary'), ('G', 'General')], default='P', max_length=1),
        ),
    ]
