# Generated by Django 4.1.3 on 2023-02-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('timelog', '0005_timelog_stopped'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('upper_limit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
