# Generated by Django 4.1.3 on 2023-02-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0007_remove_durationpackage_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durationpackage',
            name='lower_limit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='durationpackage',
            name='upper_limit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
