# Generated by Django 4.1.3 on 2023-02-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0008_alter_durationpackage_lower_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelog',
            options={'permissions': [('view_countdown_timer_duration', 'Can view countdown timer duration')]},
        ),
    ]
