# Generated by Django 4.1.3 on 2023-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docusignenvelope',
            name='signed_up_at',
        ),
        migrations.AddField(
            model_name='docusignenvelope',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
